INSERT INTO BRANDS VALUES(1, 'Adidas');
INSERT INTO BRANDS VALUES(2, 'Nike');
INSERT INTO BRANDS VALUES(3, 'Puma');
INSERT INTO BRANDS VALUES(4, 'Reebok');



INSERT INTO PRODUCT_TYPE VALUES(1, 'Shirt');
INSERT INTO PRODUCT_TYPE VALUES(2, 'Cap');
INSERT INTO PRODUCT_TYPE VALUES(3, 'Shoe');
INSERT INTO PRODUCT_TYPE VALUES(4, 'Socks');



INSERT INTO SUPPLIERS VALUES(1, 'MukherjeeSuppliers');
INSERT INTO SUPPLIERS VALUES(2, 'AniruddhaRetail');
INSERT INTO SUPPLIERS VALUES(3, 'WSRetail');
INSERT INTO SUPPLIERS VALUES(4, 'AMRetail');


INSERT INTO PRODUCTS(ID,NAME,BRAND,TYPE,SUPPLIER,AVAILABLE_COUNT,PRICE,SIZE,COLOR) VALUES(1,'Adidas Shirt-1',1,1,1,1000,500.50,40,'Green');
INSERT INTO PRODUCTS(ID,NAME,BRAND,TYPE,SUPPLIER,AVAILABLE_COUNT,PRICE,SIZE,COLOR) VALUES(2,'Nike Cap-1',2,2,2,5000,200.25,36,'Yellow');
INSERT INTO PRODUCTS(ID,NAME,BRAND,TYPE,SUPPLIER,AVAILABLE_COUNT,PRICE,SIZE,COLOR) VALUES(3,'Puma Shoe-1',3,3,3,5000,1700.25,34,'Brown');
INSERT INTO PRODUCTS(ID,NAME,BRAND,TYPE,SUPPLIER,AVAILABLE_COUNT,PRICE,SIZE,COLOR) VALUES(4,'Reebok Socks-1',4,4,4,5000,200.25,32,'Orange');